### ISSUE TITLE
Actions: build step failed

### ISSUE THREAD

**Issue by sikmir** [nix-community/nur-packages-template#52]
Build step failled:
```
Run nix run -I 'nixpkgs=channel:nixos-unstable' nixpkgs.nix-build-uncached -c nix-build-uncached ci.nix -A cacheOutputs
error: unrecognised flag '-c'
Try 'nix --help' for more information.
Error: Process completed with exit code 1.
```
https://github.com/nix-community/nur-packages-template/blob/06f4996ba197253fc671ec3be218fe5aa922caa3/.github/workflows/build.yml#L67-L69

See https://github.com/NixOS/nix/issues/5081

**Comment by Mic92** [comment]
Did nix 2.4 already hit the channels

**Comment by 0x4A6F** [comment]
[Not yet](https://nixpk.gs/pr-tracker.html?pr=144197).

**Comment by DeeUnderscore** [comment]
https://nixos.org/nix/install points to 2.4 now, so that's what `cachix/install-nix-action` ends up using

**Comment by Mic92** [comment]
fixed in https://github.com/nix-community/nur-packages-template/pull/53

**Comment by sikmir** [comment]
Doesn't work for me:
```
Nix won't work in active shell sessions until you restart them.

/nix:
Error: unable to perform operation.  (-400)
	Error: unknown indexing state.
child_process.js:642
    throw err;
    ^

Error: Command failed: /Users/runner/work/_actions/cachix/install-nix-action/v14/lib/install-nix.sh
    at checkExecSyncError (child_process.js:621:11)
    at Object.execFileSync (child_process.js:639:15)
    at Object.<anonymous> (/Users/runner/work/_actions/cachix/install-nix-action/v14/lib/main.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 945,
  stdout: null,
  stderr: null
}
```
